version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - postgres
    environment:
      PORT: 8080
      CONNECTION_STRING: postgres://postgres:root@postgres/backend_restapi
      JWT_SECRET: 7b8800a692ec26266a8d1d228369e1ae8b785685302f16b17baf7740e04d73712bc5f02722876238461462ed46989c58aca6bc245c016603ccd300b78ba45896
      JWT_EXPIRES_IN: 1d
    ports:
      - '8080:8080'
    restart: always

  postgres:
    image: postgres:15.0-alpine3.16
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'backend_restapi'
    volumes:
      - api-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

volumes:
  api-db: {}
