version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - postgres
    environment:
      PORT: 8080
      POSTGRES_DB: 'backend_restapi'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_HOST: 'postgres'
    ports:
      - '8080:8080'
    restart: always

  postgres:
    image: postgres:15.0-alpine3.16
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'backend_restapi'
    volumes:
      - api-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

volumes:
  api-db: {}
