services:
  - type: web
    env: node
    name: api-node
    repo: https://github.com/nikolaichub/backend-restapi.git
    region: frankfurt
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8080
      - key: CONNECTION_STRING
        fromDatabase:
          name: db-postgres
          property: connectionString

databases:
  - name: db-postgres
    region: frankfurt
    plan: free
    host: postgres
    port: 5432
    databas: backend_restapi
    user: postgres
    password: root
    connectionString: postgres://postgres:root@postgres:5432/backend_restapi
    postgresMajorVersion: 14
